/**
 * Single-comment ship-it verdict poster.
 *
 * Reuses pr-comment-shared/gh.ts (rule-of-four now: judges, adversarial,
 * density, ship-it summary). Same ASICODE_PR_COMMENT_ENABLED gate.
 *
 * Skip-when-empty: if signalsAvailable=0, no signals exist yet — don't
 * post. The user wouldn't see anything different than what was already
 * in the per-signal comments anyway.
 */

import { findPrNumberForSha, postPrComment } from '../pr-comment-shared/gh.js'
import type { ShipItResult } from './aggregate.js'

export interface PostShipItInput {
  prSha: string
  result: ShipItResult
  repoPath: string
}

export interface PostShipItResult {
  posted: boolean
  reason?: 'opt_out' | 'no_signals' | 'no_pr' | 'gh_failed'
  prNumber?: number
  bodyPreview?: string
}

const SHIPIT_MARKER = '<!-- asicode-ship-it-verdict -->'

export function isPrCommentEnabled(): boolean {
  return process.env.ASICODE_PR_COMMENT_ENABLED === '1'
}

export function buildShipItMarkdown(result: ShipItResult): string {
  const lines: string[] = []
  lines.push(SHIPIT_MARKER)

  const glyph =
    result.verdict === 'ship_it' ? '🟢' : result.verdict === 'hold' ? '🟡' : '🔴'
  const label =
    result.verdict === 'ship_it'
      ? 'ship it'
      : result.verdict === 'hold'
        ? 'hold'
        : 'rollback'
  lines.push(`### ${glyph} asicode verdict: **${label}**`)
  lines.push('')

  if (result.signalsAvailable === 0) {
    lines.push('_No quality signals available yet — judges/adversarial/density still pending._')
    lines.push('')
  } else if (result.signalsAvailable < 3) {
    lines.push(
      `_Verdict based on ${result.signalsAvailable}/3 signals — others still pending._`,
    )
    lines.push('')
  }

  if (result.reasons.length > 0) {
    for (const r of result.reasons) {
      lines.push(`- ${r}`)
    }
    lines.push('')
  }

  // Signal table for at-a-glance comparison with the per-signal comments.
  lines.push('| Signal | State |')
  lines.push('|---|---|')
  lines.push(
    `| judges | ${
      result.judges.rowsFound === 0
        ? '— pending'
        : `${result.judges.compositeScore?.toFixed(1) ?? '?'}/5 ${
            result.judges.panelComplete ? '✓ complete' : '⚠ partial'
          }`
    } |`,
  )
  lines.push(
    `| adversarial | ${
      !result.adversarial.ran
        ? '— pending'
        : `${result.adversarial.critical}c / ${result.adversarial.high}h / ${result.adversarial.medium}m`
    } |`,
  )
  lines.push(
    `| density | ${
      !result.density.ran
        ? '— pending'
        : !result.density.isRefactor
          ? 'non-refactor (not scored)'
          : result.density.densityDelta === null
            ? 'delta unavailable'
            : `${result.density.densityDelta >= 0 ? '+' : ''}${result.density.densityDelta} LOC`
    } |`,
  )
  lines.push('')
  lines.push(
    `<sub>Generated by asicode ship-it aggregator · <code>ASICODE_PR_COMMENT_ENABLED=1</code></sub>`,
  )
  return lines.join('\n')
}

export async function postShipItVerdict(
  input: PostShipItInput,
): Promise<PostShipItResult> {
  if (!isPrCommentEnabled()) return { posted: false, reason: 'opt_out' }
  if (input.result.signalsAvailable === 0) {
    return { posted: false, reason: 'no_signals' }
  }

  const prNumber = await findPrNumberForSha(input.prSha, input.repoPath)
  if (prNumber === null) return { posted: false, reason: 'no_pr' }

  const body = buildShipItMarkdown(input.result)
  const posted = await postPrComment({ prNumber, repoPath: input.repoPath, body })
  if (!posted) {
    return {
      posted: false,
      reason: 'gh_failed',
      prNumber,
      bodyPreview: body.slice(0, 200),
    }
  }
  return { posted: true, prNumber, bodyPreview: body.slice(0, 200) }
}
