/**
 * Post the 3-panel judge verdict as a GitHub PR comment.
 *
 * Why: judges write rows to the SQLite db, but the user has no way to
 * SEE the verdict short of running `instrumentation:report`. Posting
 * the verdict on the PR itself makes "verifiably correct PR" visible
 * in the place the user is already looking — the GitHub UI.
 *
 * Opt-in via ASICODE_PR_COMMENT_ENABLED=1. Soft-fails on missing gh,
 * unauthenticated gh, network errors. Never blocks the merge path —
 * the judges trigger calls this after dispatch completes and ignores
 * the return.
 *
 * Idempotency: each comment is tagged with an HTML marker
 * `<!-- asicode-judge-verdict -->` so re-runs can be detected. v1
 * just adds a comment; v2 could replace via `gh pr comment --edit-last`
 * once that pattern proves out.
 */

import { findPrNumberForSha, postPrComment } from '../pr-comment-shared/gh.js'
import type { DispatchResult, JudgeResult } from './dispatcher.js'

export interface PostCommentInput {
  prSha: string
  result: DispatchResult
  repoPath: string
}

export interface PostCommentResult {
  posted: boolean
  reason?: 'opt_out' | 'gh_missing' | 'gh_failed' | 'no_pr' | 'panel_empty' | 'already_posted'
  prNumber?: number
  bodyPreview?: string
}

const VERDICT_MARKER = '<!-- asicode-judge-verdict -->'

export function isPrCommentEnabled(): boolean {
  return process.env.ASICODE_PR_COMMENT_ENABLED === '1'
}

/**
 * Pretty-print a 1-5 score as "N/5" plus a glyph for at-a-glance
 * scanning. Color-coded glyphs would be nicer but GitHub markdown
 * doesn't render arbitrary ANSI.
 */
function formatScore(n: number): string {
  const rounded = Math.round(n * 10) / 10
  const glyph = n >= 4.5 ? '🟢' : n >= 3.5 ? '🟡' : '🔴'
  return `${glyph} ${rounded}/5`
}

/**
 * Build the markdown body. Public so callers (CLI, tests) can render
 * without actually posting.
 */
export function buildVerdictMarkdown(result: DispatchResult): string {
  const lines: string[] = []
  lines.push(VERDICT_MARKER)
  lines.push('### asicode judge verdict')
  lines.push('')

  if (!result.complete) {
    const okJudges = result.judges.filter(j => j.ok).length
    lines.push(`> ⚠️ Partial panel: ${okJudges}/${result.judges.length} judges responded.`)
    lines.push('')
  }

  // Per-role row with the role's own primary score.
  lines.push('| Role | Score | Concerns | Model |')
  lines.push('|---|---|---|---|')
  for (const j of result.judges) {
    if (j.ok) {
      const score = j.response.scores[j.role]
      const concernCount = j.response.concerns.length
      const concernCell = concernCount === 0 ? '—' : `${concernCount}`
      lines.push(`| ${j.role.replace('_', ' ')} | ${formatScore(score)} | ${concernCell} | \`${j.model}\` |`)
    } else {
      lines.push(`| ${j.role.replace('_', ' ')} | — failed | — | \`${j.model}\` (${j.kind}) |`)
    }
  }
  lines.push('')

  // Concerns section: list any non-low concerns inline, collapsed if
  // verbose. Caller can opt out with --no-concerns in a future flag.
  const allConcerns = result.judges
    .filter((j): j is JudgeResult & { ok: true } => j.ok)
    .flatMap(j =>
      j.response.concerns.map(c => ({
        role: j.role,
        severity: c.severity,
        description: c.description,
      })),
    )
  const nonLow = allConcerns.filter(c => c.severity !== 'low')
  if (nonLow.length > 0) {
    lines.push('**Concerns flagged:**')
    for (const c of nonLow) {
      const tag = c.severity === 'high' ? '🔴 high' : '🟡 med'
      lines.push(`- ${tag} (${c.role.replace('_', ' ')}): ${c.description}`)
    }
    lines.push('')
  }

  // Aggregate footer.
  const composite =
    result.judges
      .filter((j): j is JudgeResult & { ok: true } => j.ok)
      .reduce(
        (sum, j) =>
          sum + (j.response.scores.correctness + j.response.scores.code_review + j.response.scores.qa_risk) / 3,
        0,
      ) / Math.max(result.judges.filter(j => j.ok).length, 1)
  lines.push(`Composite: **${(Math.round(composite * 10) / 10).toFixed(1)}/5**`)
  lines.push('')
  lines.push(`<sub>Generated by asicode • <code>ASICODE_PR_COMMENT_ENABLED=1</code></sub>`)

  return lines.join('\n')
}

/**
 * Post the verdict comment via the shared gh plumbing. Returns a
 * structured result describing what happened (so callers can log).
 */
export async function postJudgeVerdict(input: PostCommentInput): Promise<PostCommentResult> {
  if (!isPrCommentEnabled()) return { posted: false, reason: 'opt_out' }
  if (input.result.judges.length === 0) return { posted: false, reason: 'panel_empty' }

  const prNumber = await findPrNumberForSha(input.prSha, input.repoPath)
  if (prNumber === null) return { posted: false, reason: 'no_pr' }

  const body = buildVerdictMarkdown(input.result)
  const outcome = await postPrComment({
    prNumber,
    repoPath: input.repoPath,
    body,
    idempotencyMarker: VERDICT_MARKER,
  })

  if (outcome === 'already_posted') {
    return { posted: false, reason: 'already_posted', prNumber, bodyPreview: body.slice(0, 200) }
  }
  if (outcome === 'failed') {
    return { posted: false, reason: 'gh_failed', prNumber, bodyPreview: body.slice(0, 200) }
  }
  return { posted: true, prNumber, bodyPreview: body.slice(0, 200) }
}
