/**
 * Post the 3-panel judge verdict as a GitHub PR comment.
 *
 * Why: judges write rows to the SQLite db, but the user has no way to
 * SEE the verdict short of running `instrumentation:report`. Posting
 * the verdict on the PR itself makes "verifiably correct PR" visible
 * in the place the user is already looking — the GitHub UI.
 *
 * Opt-in via ASICODE_PR_COMMENT_ENABLED=1. Soft-fails on missing gh,
 * unauthenticated gh, network errors. Never blocks the merge path —
 * the judges trigger calls this after dispatch completes and ignores
 * the return.
 *
 * Idempotency: each comment is tagged with an HTML marker
 * `<!-- asicode-judge-verdict -->` so re-runs can be detected. v1
 * just adds a comment; v2 could replace via `gh pr comment --edit-last`
 * once that pattern proves out.
 */

import { spawn } from 'node:child_process'
import type { DispatchResult, JudgeResult } from './dispatcher.js'

export interface PostCommentInput {
  prSha: string
  result: DispatchResult
  repoPath: string
}

export interface PostCommentResult {
  posted: boolean
  reason?: 'opt_out' | 'gh_missing' | 'gh_failed' | 'no_pr' | 'panel_empty'
  prNumber?: number
  bodyPreview?: string
}

const VERDICT_MARKER = '<!-- asicode-judge-verdict -->'

export function isPrCommentEnabled(): boolean {
  return process.env.ASICODE_PR_COMMENT_ENABLED === '1'
}

/**
 * Pretty-print a 1-5 score as "N/5" plus a glyph for at-a-glance
 * scanning. Color-coded glyphs would be nicer but GitHub markdown
 * doesn't render arbitrary ANSI.
 */
function formatScore(n: number): string {
  const rounded = Math.round(n * 10) / 10
  const glyph = n >= 4.5 ? '🟢' : n >= 3.5 ? '🟡' : '🔴'
  return `${glyph} ${rounded}/5`
}

/**
 * Build the markdown body. Public so callers (CLI, tests) can render
 * without actually posting.
 */
export function buildVerdictMarkdown(result: DispatchResult): string {
  const lines: string[] = []
  lines.push(VERDICT_MARKER)
  lines.push('### asicode judge verdict')
  lines.push('')

  if (!result.complete) {
    const okJudges = result.judges.filter(j => j.ok).length
    lines.push(`> ⚠️ Partial panel: ${okJudges}/${result.judges.length} judges responded.`)
    lines.push('')
  }

  // Per-role row with the role's own primary score.
  lines.push('| Role | Score | Concerns | Model |')
  lines.push('|---|---|---|---|')
  for (const j of result.judges) {
    if (j.ok) {
      const score = j.response.scores[j.role]
      const concernCount = j.response.concerns.length
      const concernCell = concernCount === 0 ? '—' : `${concernCount}`
      lines.push(`| ${j.role.replace('_', ' ')} | ${formatScore(score)} | ${concernCell} | \`${j.model}\` |`)
    } else {
      lines.push(`| ${j.role.replace('_', ' ')} | — failed | — | \`${j.model}\` (${j.kind}) |`)
    }
  }
  lines.push('')

  // Concerns section: list any non-low concerns inline, collapsed if
  // verbose. Caller can opt out with --no-concerns in a future flag.
  const allConcerns = result.judges
    .filter((j): j is JudgeResult & { ok: true } => j.ok)
    .flatMap(j =>
      j.response.concerns.map(c => ({
        role: j.role,
        severity: c.severity,
        description: c.description,
      })),
    )
  const nonLow = allConcerns.filter(c => c.severity !== 'low')
  if (nonLow.length > 0) {
    lines.push('**Concerns flagged:**')
    for (const c of nonLow) {
      const tag = c.severity === 'high' ? '🔴 high' : '🟡 med'
      lines.push(`- ${tag} (${c.role.replace('_', ' ')}): ${c.description}`)
    }
    lines.push('')
  }

  // Aggregate footer.
  const composite =
    result.judges
      .filter((j): j is JudgeResult & { ok: true } => j.ok)
      .reduce(
        (sum, j) =>
          sum + (j.response.scores.correctness + j.response.scores.code_review + j.response.scores.qa_risk) / 3,
        0,
      ) / Math.max(result.judges.filter(j => j.ok).length, 1)
  lines.push(`Composite: **${(Math.round(composite * 10) / 10).toFixed(1)}/5**`)
  lines.push('')
  lines.push(`<sub>Generated by asicode • <code>ASICODE_PR_COMMENT_ENABLED=1</code></sub>`)

  return lines.join('\n')
}

/**
 * Find the PR number for a given merge sha by asking gh. Returns null
 * when gh isn't available or the sha doesn't map to a PR (e.g. the
 * commit was pushed directly to main without a PR).
 */
async function findPrNumberForSha(prSha: string, repoPath: string): Promise<number | null> {
  return new Promise(resolve => {
    let out = ''
    let settled = false
    const child = spawn(
      'gh',
      [
        'pr',
        'list',
        '--state',
        'merged',
        '--search',
        prSha,
        '--json',
        'number,mergeCommit',
        '--limit',
        '5',
      ],
      { cwd: repoPath, stdio: ['ignore', 'pipe', 'ignore'] },
    )
    const timer = setTimeout(() => {
      child.kill()
      if (!settled) {
        settled = true
        resolve(null)
      }
    }, 10_000)
    child.stdout.on('data', (chunk: Buffer) => {
      out += chunk.toString('utf-8')
    })
    child.on('error', () => {
      clearTimeout(timer)
      if (!settled) {
        settled = true
        resolve(null)
      }
    })
    child.on('close', code => {
      clearTimeout(timer)
      if (settled) return
      settled = true
      if (code !== 0) return resolve(null)
      try {
        const parsed = JSON.parse(out) as Array<{ number: number; mergeCommit: { oid: string } | null }>
        const match = parsed.find(p => p.mergeCommit && p.mergeCommit.oid === prSha)
        resolve(match ? match.number : null)
      } catch {
        resolve(null)
      }
    })
  })
}

/**
 * Post the verdict comment via `gh pr comment N --body-file -`. Returns
 * a structured result describing what happened (so callers can log).
 */
export async function postJudgeVerdict(input: PostCommentInput): Promise<PostCommentResult> {
  if (!isPrCommentEnabled()) return { posted: false, reason: 'opt_out' }
  if (input.result.judges.length === 0) return { posted: false, reason: 'panel_empty' }

  const prNumber = await findPrNumberForSha(input.prSha, input.repoPath)
  if (prNumber === null) return { posted: false, reason: 'no_pr' }

  const body = buildVerdictMarkdown(input.result)

  // gh pr comment <N> --body-file - reads body from stdin so we don't
  // have to argv-escape a multi-line markdown blob. Cleaner than --body
  // with quoting tricks.
  const posted = await new Promise<boolean>(resolve => {
    let settled = false
    const child = spawn(
      'gh',
      ['pr', 'comment', String(prNumber), '--body-file', '-'],
      { cwd: input.repoPath, stdio: ['pipe', 'ignore', 'pipe'] },
    )
    const timer = setTimeout(() => {
      child.kill()
      if (!settled) {
        settled = true
        resolve(false)
      }
    }, 15_000)
    child.on('error', () => {
      clearTimeout(timer)
      if (!settled) {
        settled = true
        resolve(false)
      }
    })
    child.on('close', code => {
      clearTimeout(timer)
      if (settled) return
      settled = true
      resolve(code === 0)
    })
    child.stdin.end(body)
  })

  if (!posted) {
    return { posted: false, reason: 'gh_failed', prNumber, bodyPreview: body.slice(0, 200) }
  }
  return { posted: true, prNumber, bodyPreview: body.slice(0, 200) }
}
