/**
 * Post A15 adversarial findings as a GitHub PR comment.
 *
 * Why: the verifier finds genuine attack surface in merged code, but
 * those findings only live in the reviews table. Posting them on the
 * PR thread surfaces the work to the user — they can rollback, follow
 * up, or just see what asicode noticed.
 *
 * Opt-in: ASICODE_PR_COMMENT_ENABLED=1 (same flag as iter 54's judge
 * verdict — turning it on enables BOTH; one less env var to manage).
 *
 * Skip-when-empty: if the verifier found zero non-low findings, don't
 * post. The PR thread isn't a place for "no issues found" — that's
 * what the judge verdict comment is for.
 */

import { findPrNumberForSha, postPrComment } from '../pr-comment-shared/gh.js'
import type { Finding, VerifierResponse } from './verifier.js'

export interface PostAdversarialInput {
  prSha: string
  response: VerifierResponse
  repoPath: string
}

export interface PostAdversarialResult {
  posted: boolean
  reason?: 'opt_out' | 'no_actionable_findings' | 'no_pr' | 'gh_failed' | 'already_posted'
  prNumber?: number
  bodyPreview?: string
}

const ADVERSARIAL_MARKER = '<!-- asicode-adversarial-findings -->'

export function isPrCommentEnabled(): boolean {
  return process.env.ASICODE_PR_COMMENT_ENABLED === '1'
}

/**
 * Build the markdown body. Public so callers can render without posting.
 */
export function buildFindingsMarkdown(response: VerifierResponse): string {
  const lines: string[] = []
  lines.push(ADVERSARIAL_MARKER)
  lines.push('### asicode adversarial findings')
  lines.push('')

  const bySev = groupBySeverity(response.findings)
  const critical = bySev.critical.length
  const high = bySev.high.length
  const medium = bySev.medium.length
  const low = bySev.low.length

  // One-line summary row before the details.
  const counts: string[] = []
  if (critical) counts.push(`🔴 ${critical} critical`)
  if (high) counts.push(`🔴 ${high} high`)
  if (medium) counts.push(`🟡 ${medium} medium`)
  if (low) counts.push(`⚪ ${low} low`)
  lines.push(counts.length ? `**${counts.join(' · ')}**` : '_No findings reported._')
  lines.push('')

  for (const sev of ['critical', 'high', 'medium'] as const) {
    if (bySev[sev].length === 0) continue
    const glyph = sev === 'medium' ? '🟡' : '🔴'
    lines.push(`#### ${glyph} ${sev}`)
    for (const f of bySev[sev]) {
      lines.push(`- **${f.title}**`)
      lines.push(`  ${f.specifics}`)
      if (f.suggested_fix) {
        lines.push(`  _Suggested fix:_ ${f.suggested_fix}`)
      }
    }
    lines.push('')
  }

  // Verifier's own one-line summary, indented.
  lines.push(`> ${response.summary}`)
  lines.push('')
  const confidencePct = Math.round(response.confidence * 100)
  lines.push(
    `<sub>Generated by asicode adversarial verifier · confidence ${confidencePct}% · <code>ASICODE_PR_COMMENT_ENABLED=1</code></sub>`,
  )

  return lines.join('\n')
}

function groupBySeverity(findings: Finding[]): Record<Finding['severity'], Finding[]> {
  const out: Record<Finding['severity'], Finding[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
  }
  for (const f of findings) out[f.severity].push(f)
  return out
}

/**
 * Does this response have findings worth posting? Low-only and empty
 * responses are not posted — the PR thread shouldn't be spammed with
 * "no issues" noise. The judge verdict comment is the place for the
 * "everything looks good" signal.
 */
export function hasActionableFindings(response: VerifierResponse): boolean {
  return response.findings.some(f => f.severity !== 'low')
}

/**
 * Post the adversarial findings comment. Returns a structured result.
 */
export async function postAdversarialFindings(
  input: PostAdversarialInput,
): Promise<PostAdversarialResult> {
  if (!isPrCommentEnabled()) return { posted: false, reason: 'opt_out' }
  if (!hasActionableFindings(input.response)) {
    return { posted: false, reason: 'no_actionable_findings' }
  }

  const prNumber = await findPrNumberForSha(input.prSha, input.repoPath)
  if (prNumber === null) return { posted: false, reason: 'no_pr' }

  const body = buildFindingsMarkdown(input.response)
  const outcome = await postPrComment({
    prNumber,
    repoPath: input.repoPath,
    body,
    idempotencyMarker: ADVERSARIAL_MARKER,
  })

  if (outcome === 'already_posted') {
    return { posted: false, reason: 'already_posted', prNumber, bodyPreview: body.slice(0, 200) }
  }
  if (outcome === 'failed') {
    return { posted: false, reason: 'gh_failed', prNumber, bodyPreview: body.slice(0, 200) }
  }
  return { posted: true, prNumber, bodyPreview: body.slice(0, 200) }
}
