/**
 * Post the density A/B summary as a GitHub PR comment.
 *
 * Why: density is the third quality signal (after judges/iter-54 and
 * adversarial/iter-55). Posting it on the PR closes the visibility
 * loop — the user sees the asi-aesthetic verdict ("denser by N LOC,
 * tests still pass, judges saw the patches as equivalent") in the
 * same place they see the other signals.
 *
 * Skip-when-noise: non-refactor PRs would post "not a refactor; nothing
 * to score" 90% of the time. We only post when isRefactor=true.
 *
 * Skip-when-no-delta: refactor that produced LOC delta=null (git diff
 * failed) has nothing useful to say. Skip.
 *
 * Opt-in: same ASICODE_PR_COMMENT_ENABLED=1 flag as iters 54-55. One
 * env var controls all three; reduce config surface.
 */

import { findPrNumberForSha, postPrComment } from '../pr-comment-shared/gh.js'
import type { RecordDensityResult } from './density.js'

export interface PostDensityInput {
  prSha: string
  result: RecordDensityResult
  repoPath: string
}

export interface PostDensityResult {
  posted: boolean
  reason?:
    | 'opt_out'
    | 'not_a_refactor'
    | 'no_delta'
    | 'no_pr'
    | 'gh_failed'
  prNumber?: number
  bodyPreview?: string
}

const DENSITY_MARKER = '<!-- asicode-density-summary -->'

export function isPrCommentEnabled(): boolean {
  return process.env.ASICODE_PR_COMMENT_ENABLED === '1'
}

/**
 * Build the markdown body. Public so callers (tests, CLI) can render
 * without posting.
 *
 * density_delta semantics (from density.ts): positive = denser
 * (fewer net LOC for equivalent behavior); negative = bloated. The
 * absolute value is the LOC count. So delta=12 means "12 lines
 * shorter than baseline for the same tests."
 */
export function buildDensitySummaryMarkdown(result: RecordDensityResult): string {
  const lines: string[] = []
  lines.push(DENSITY_MARKER)
  lines.push('### asicode density A/B')
  lines.push('')

  const delta = result.densityDelta
  const denser = delta !== null && delta > 0
  const bloated = delta !== null && delta < 0

  if (delta !== null) {
    const verdict = denser
      ? `🟢 **denser by ${delta} LOC**`
      : bloated
        ? `🟡 **bloated by ${Math.abs(delta)} LOC**`
        : '⚪ **neutral** (0 LOC delta)'
    lines.push(verdict)
  } else {
    lines.push('⚪ LOC delta unavailable')
  }
  lines.push('')

  // Gate detail table — shows the user *why* density was/wasn't counted.
  lines.push('| Gate | Status |')
  lines.push('|---|---|')
  const testsCell =
    result.testsPassSetIsSuperset === true
      ? '✓ pre-test pass set ⊆ post-test pass set'
      : result.testsPassSetIsSuperset === false
        ? '✗ tests regressed'
        : '– not measured (no test runner)'
  lines.push(`| tests still passing | ${testsCell} |`)

  const judgeCell =
    result.judgeEquivalenceScore === null
      ? '– not measured (judges not run)'
      : result.judgeEquivalenceScore >= 0
        ? `✓ judges saw equivalent behavior (${result.judgeEquivalenceScore.toFixed(1)})`
        : `✗ judges flagged behavior drift (${result.judgeEquivalenceScore.toFixed(1)})`
  lines.push(`| judge equivalence | ${judgeCell} |`)

  const countedCell = result.densityCounted
    ? '✓ counts toward density-on-refactors metric'
    : `✗ does not count${result.notCountedReason ? ` (${result.notCountedReason})` : ''}`
  lines.push(`| metric counted | ${countedCell} |`)
  lines.push('')

  // One-line footer.
  lines.push(
    `<sub>Generated by asicode density A/B harness · <code>ASICODE_PR_COMMENT_ENABLED=1</code></sub>`,
  )

  return lines.join('\n')
}

/**
 * Decide whether a result is worth posting. Non-refactors and missing
 * deltas would be noise.
 */
export function shouldPostDensity(result: RecordDensityResult): {
  shouldPost: boolean
  reason?: 'not_a_refactor' | 'no_delta'
} {
  // recordDensity uses notCountedReason='not a refactor' on the
  // non-refactor branch and stores no abId... actually abId IS set on
  // the non-refactor branch (a row is still recorded for audit). The
  // distinguishing field is densityDelta: null on non-refactor, set on
  // refactor.
  if (result.notCountedReason === 'not a refactor') {
    return { shouldPost: false, reason: 'not_a_refactor' }
  }
  if (result.densityDelta === null) {
    return { shouldPost: false, reason: 'no_delta' }
  }
  return { shouldPost: true }
}

/**
 * Post the density summary. Returns a structured result.
 */
export async function postDensitySummary(
  input: PostDensityInput,
): Promise<PostDensityResult> {
  if (!isPrCommentEnabled()) return { posted: false, reason: 'opt_out' }

  const should = shouldPostDensity(input.result)
  if (!should.shouldPost) return { posted: false, reason: should.reason }

  const prNumber = await findPrNumberForSha(input.prSha, input.repoPath)
  if (prNumber === null) return { posted: false, reason: 'no_pr' }

  const body = buildDensitySummaryMarkdown(input.result)
  const posted = await postPrComment({ prNumber, repoPath: input.repoPath, body })

  if (!posted) {
    return { posted: false, reason: 'gh_failed', prNumber, bodyPreview: body.slice(0, 200) }
  }
  return { posted: true, prNumber, bodyPreview: body.slice(0, 200) }
}
